### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ADAGAMLUCA** [ikt32/GTAVManualTransmission#173] opened 2024-07-30 02:32 UTC
**Describe the bug**
the motorcycles are working but the cars and others are not, but the wheel is detected

**Screenshots and/or videos**

**Used versions and additional hardware:**
 - Game version: [1.0.3274.0_v2 on epic)
 - Mod version: [v5.6.1]
 - Additional hardware: [e.g. Logitech G29]

**Screenshots and/or videos**

https://github.com/user-attachments/assets/248bcfd8-0374-499e-9bfb-f60c7a5e7a93

**Settings, if applicable:**
[settings_controls.txt](https://github.com/user-attachments/files/16421235/settings_controls.txt)
[settings_general.txt](https://github.com/user-attachments/files/16421236/settings_general.txt)

**Comment by ikt32** [comment] 2024-07-30 05:30
Closing as duplicate of #148

**Closed by ikt32** 2024-07-30 05:30 UTC
Labels: bug
