### ISSUE TITLE
[BUG] After installing the mod, cars can no longer be turned.

### ISSUE THREAD

**Issue by BATL3R** [ikt32/GTAVManualTransmission#166] opened 2024-04-15 17:18 UTC
After installing the mod, cars can no longer be turned. It seems like the steering wheel is visually spinning, but the wheels are not physically turning. What to do?

**Comment by Highland-ai** [comment] 2024-04-15 18:15
I can also confirm this issue.

**Comment by CKAY-9** [comment] 2024-04-19 23:40
I managed to get steering working with the mod; however, I had to disable the "enhanced steering" in Controls > Steering Assists. Not an optimal fix but I don't mind for an outdated mod.

**Comment by ikt32** [comment] 2024-04-20 11:08
Duplicate of #148. (Yes, the steering patching is broken, among with other stuff).

**Closed by ikt32** 2024-04-20 11:08 UTC
Labels: bug
