### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SpaimaFemeilor** [ikt32/GTAVManualTransmission#150] opened 2023-12-18 14:10 UTC
**Describe the bug**
Wheels of the car dont turn
**To Reproduce**
set up mod, put car in gear, try to turn,(interior wheel turns, but the actual wheels dont turn)
**Expected behavior**
the wheels of the car to turn
**Screenshots and/or videos**
If applicable, add screenshots or video to help explain your problem.
![image](https://github.com/ikt32/GTAVManualTransmission/assets/119695841/f298201e-fa07-406d-b3a4-20e96ac8b070)

**Used versions and additional hardware:**
[settings_wheel - Copie.txt](https://github.com/ikt32/GTAVManualTransmission/files/13704754/settings_wheel.-.Copie.txt)
 - 3095, epic games
 - Mod version: 5.6.1
 - Additional hardware: logitech g29
**Settings, if applicable:**

 - If applicable, link to settings_general.ini
 - If applicable, [settings_wheel - Copie.txt](https://github.com/ikt32/GTAVManualTransmission/files/13704754/settings_wheel.-.Copie.txt)
(file is ini in game files, couldnt upload ini)
**Additional context**
everything works perfectly, but the wheels of the cars dont turn. interior steering wheel works

**Comment by ikt32** [comment] 2023-12-18 14:21
Duplicate of #148

**Closed by ikt32** 2023-12-18 14:21 UTC
Labels: bug
